//
//  MainTabBarViewController.swift
//  Cinematics
//
//  Created by Nghia Nguyen on 4/13/20.
//  Copyright (c) 2020 Nghia Nguyen. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import RxCocoa
import RxSwift
import UIKit

final class MainTabBarViewController: UITabBarController {
    // MARK: - Public properties -

    var presenter: MainTabBarPresenterInterface!

    // MARK: - Private properties -

    private let disposeBag = DisposeBag()

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        setupView()
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        navigationController?.setNavigationBarHidden(true, animated: true)
    }
}

// MARK: - Extensions -

extension MainTabBarViewController: MainTabBarViewInterface {}

private extension MainTabBarViewController {
    func setupView() {
        tabBar.tintColor = R.color.cd6182A()!
        tabBar.backgroundColor = .white
        tabBar.backgroundImage = UIImage()
    }
}
