//
//  MainTabBarInterfaces.swift
//  Cinematics
//
//  Created by Nghia Nguyen on 4/13/20.
//  Copyright (c) 2020 Nghia Nguyen. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

enum MainTabBar {

    struct ViewOutput {
    }

    struct ViewInput {
    }

}

protocol MainTabBarWireframeInterface: WireframeInterface {
}

protocol MainTabBarViewInterface: ViewInterface {
}

protocol MainTabBarPresenterInterface: PresenterInterface {
    func configure(with output: MainTabBar.ViewOutput) -> MainTabBar.ViewInput
}

protocol MainTabBarInteractorInterface: InteractorInterface {
}
