//
//  MainTabBarPresenter.swift
//  Cinematics
//
//  Created by Nghia Nguyen on 4/13/20.
//  Copyright (c) 2020 Nghia Nguyen. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import RxSwift
import RxCocoa

final class MainTabBarPresenter {

    // MARK: - Private properties -

    private unowned let view: MainTabBarViewInterface
    private let interactor: MainTabBarInteractorInterface
    private let wireframe: MainTabBarWireframeInterface

    // MARK: - Lifecycle -

    init(view: MainTabBarViewInterface, interactor: MainTabBarInteractorInterface, wireframe: MainTabBarWireframeInterface) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension MainTabBarPresenter: MainTabBarPresenterInterface {

    func configure(with output: MainTabBar.ViewOutput) -> MainTabBar.ViewInput {
        return MainTabBar.ViewInput()
    }

}
