//
//  MainTabBarWireframe.swift
//  Cinematics
//
//  Created by Nghia Nguyen on 4/13/20.
//  Copyright (c) 2020 Nghia Nguyen. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import RxCocoa
import RxSwift
import UIKit

final class MainTabBarWireframe: BaseWireframe {
    // MARK: - Private properties -

    private let moviesWireFrame = MoviesWireframe()
    private let tvWireFrame = TVWireframe()
    private let profileWireFrame = ProfileWireframe()

    // MARK: - Module setup -

    init() {
        let moduleViewController = MainTabBarViewController()
        super.init(viewController: moduleViewController)

        let interactor = MainTabBarInteractor()
        let presenter = MainTabBarPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter

        let moviesNavigation = UINavigationController(rootViewController: moviesWireFrame.viewController)
        let tvNavigation = UINavigationController(rootViewController: tvWireFrame.viewController)
        let profileNavigation = UINavigationController(rootViewController: profileWireFrame.viewController)

        moviesNavigation.tabBarItem = UITabBarItem(title: "Movies", image: R.image.tab_icon_movies_inactive()!, selectedImage: R.image.tab_icon_movies_active()!)
        tvNavigation.tabBarItem = UITabBarItem(title: "TV", image: R.image.tab_icon_tv_inactive()!, selectedImage: R.image.tab_icon_tv_active()!)
        profileNavigation.tabBarItem = UITabBarItem(title: "Profile", image: R.image.tab_icon_profile_inactive()!, selectedImage: R.image.tab_icon_profile_active()!)

        moduleViewController.setViewControllers([moviesNavigation, tvNavigation, profileNavigation], animated: false)
    }
}

// MARK: - Extensions -

extension MainTabBarWireframe: MainTabBarWireframeInterface {}
