//
//  OnboardingInterfaces.swift
//  Cinematics
//
//  Created by Nghia Nguyen on 5/31/20.
//  Copyright (c) 2020 Nghia Nguyen. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import RxCocoa
import RxSwift
import UIKit

enum OnboardingNavigationOption {
    case home
}

protocol OnboardingWireframeInterface: WireframeInterface {
    func navigate(to option: OnboardingNavigationOption)
}

protocol OnboardingViewInterface: ViewInterface {}

protocol OnboardingPresenterInterface: PresenterInterface {
    func configure(with output: Onboarding.ViewOutput) -> Onboarding.ViewInput
}

protocol OnboardingInteractorInterface: InteractorInterface {}

enum Onboarding {
    struct ViewOutput {
        var nextAction: Observable<Void>
    }

    struct ViewInput {
        var index: Driver<Int>
        var nextButtonImage: Driver<UIImage>
    }
}
