//
//  MoviesInterfaces.swift
//  Cinematics
//
//  Created by Nghia Nguyen on 4/13/20.
//  Copyright (c) 2020 Nghia Nguyen. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

enum Movies {

    struct ViewOutput {
    }

    struct ViewInput {
    }

}

protocol MoviesWireframeInterface: WireframeInterface {
}

protocol MoviesViewInterface: ViewInterface {
}

protocol MoviesPresenterInterface: PresenterInterface {
    func configure(with output: Movies.ViewOutput) -> Movies.ViewInput
}

protocol MoviesInteractorInterface: InteractorInterface {
}
