//
//  MoviesPresenter.swift
//  Cinematics
//
//  Created by Nghia Nguyen on 4/13/20.
//  Copyright (c) 2020 Nghia Nguyen. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import RxCocoa
import RxSwift

final class MoviesPresenter {
    // MARK: - Private properties -

    private unowned let view: MoviesViewInterface
    private let interactor: MoviesInteractorInterface
    private let wireframe: MoviesWireframeInterface

    // MARK: - Lifecycle -

    init(view: MoviesViewInterface, interactor: MoviesInteractorInterface, wireframe: MoviesWireframeInterface) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension MoviesPresenter: MoviesPresenterInterface {}
