//
//  MoviesInterfaces.swift
//  Cinematics
//
//  Created by Nghia Nguyen on 4/13/20.
//  Copyright (c) 2020 Nghia Nguyen. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol MoviesWireframeInterface: WireframeInterface {}

protocol MoviesViewInterface: ViewInterface {}

protocol MoviesPresenterInterface: PresenterInterface {}

protocol MoviesInteractorInterface: InteractorInterface {}
