//
//  ProfileViewController.swift
//  Cinematics
//
//  Created by Nghia Nguyen on 4/13/20.
//  Copyright (c) 2020 Nghia Nguyen. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

final class ProfileViewController: BaseViewController, NavigationBarVisible {

    // MARK: - Public properties -

    var presenter: ProfilePresenterInterface!
    var isHideNavigationBar: Bool = true

    // MARK: - Private properties -

    private let disposeBag = DisposeBag()

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        setupView()
    }

}

// MARK: - Extensions -

extension ProfileViewController: ProfileViewInterface {
}

private extension ProfileViewController {

    func setupView() {
        let output = Profile.ViewOutput()

        let input = presenter.configure(with: output)
    }

}
