//
//  ProfileFormatter.swift
//  Cinematics
//
//  Created by Nghia Nguyen on 5/31/20.
//  Copyright (c) 2020 Nghia Nguyen. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class ProfileFormatter {
}

// MARK: - Extensions -

extension ProfileFormatter: ProfileFormatterInterface {
}
