//
//  ProfileInterfaces.swift
//  Cinematics
//
//  Created by Nghia Nguyen on 5/31/20.
//  Copyright (c) 2020 Nghia Nguyen. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol ProfileWireframeInterface: WireframeInterface {
}

protocol ProfileViewInterface: ViewInterface {
}

protocol ProfilePresenterInterface: PresenterInterface {
}

protocol ProfileFormatterInterface: FormatterInterface {
}

protocol ProfileInteractorInterface: InteractorInterface {
}
