//
//  ProfileInterfaces.swift
//  Cinematics
//
//  Created by Nghia Nguyen on 4/13/20.
//  Copyright (c) 2020 Nghia Nguyen. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

enum Profile {

    struct ViewOutput {
    }

    struct ViewInput {
    }

}

protocol ProfileWireframeInterface: WireframeInterface {
}

protocol ProfileViewInterface: ViewInterface {
}

protocol ProfilePresenterInterface: PresenterInterface {
    func configure(with output: Profile.ViewOutput) -> Profile.ViewInput
}

protocol ProfileInteractorInterface: InteractorInterface {
}
