//
//  OnboardPresenter.swift
//  Cinematics
//
//  Created by Nghia Nguyen on 4/10/20.
//  Copyright (c) 2020 Nghia Nguyen. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import RxSwift
import RxCocoa

final class OnboardPresenter {

    // MARK: - Private properties -

    private unowned let view: OnboardViewInterface
    private let interactor: OnboardInteractorInterface
    private let wireframe: OnboardWireframeInterface
    
    private var currentPageIndex = 0
    private let totalPage = 3

    // MARK: - Lifecycle -

    init(view: OnboardViewInterface, interactor: OnboardInteractorInterface, wireframe: OnboardWireframeInterface) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension OnboardPresenter: OnboardPresenterInterface {
    func didNextButtonTapped() {
        if currentPageIndex < totalPage - 1 {
            currentPageIndex += 1
            let nextImage = currentPageIndex == totalPage - 1 ? R.image.get_started_button()! : R.image.next_button()!
            view.moveToNextPage(info: Onboard.ViewOutput(index: currentPageIndex, nextButtonImage: nextImage))
        } else {
            wireframe.navigate(to: .home)
        }
    }
}
