//
//  OnboardWireframe.swift
//  Cinematics
//
//  Created by Nghia Nguyen on 4/10/20.
//  Copyright (c) 2020 Nghia Nguyen. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

final class OnboardWireframe: BaseWireframe {

    // MARK: - Private properties -

    private let storyboard = UIStoryboard(name: "Onboard", bundle: nil)

    // MARK: - Module setup -

    init() {
        let moduleViewController = storyboard.instantiateViewController(ofType: OnboardViewController.self)
        super.init(viewController: moduleViewController)

        let interactor = OnboardInteractor()
        let presenter = OnboardPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension OnboardWireframe: OnboardWireframeInterface {
    func navigate(to option: OnboardNavigationOption) {
        switch option {
        case .home:
            openHome()
        }
    }
    
    private func openHome() {
        navigationController?.setRootWireframe(MainTabBarWireframe())
    }
}
