//
//  TVInterfaces.swift
//  Cinematics
//
//  Created by Nghia Nguyen on 4/13/20.
//  Copyright (c) 2020 Nghia Nguyen. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

enum TV {

    struct ViewOutput {
    }

    struct ViewInput {
    }

}

protocol TVWireframeInterface: WireframeInterface {
}

protocol TVViewInterface: ViewInterface {
}

protocol TVPresenterInterface: PresenterInterface {
    func configure(with output: TV.ViewOutput) -> TV.ViewInput
}

protocol TVInteractorInterface: InteractorInterface {
}
