//
//  TVSeriesFormatter.swift
//  Cinematics
//
//  Created by Nghia Nguyen on 5/31/20.
//  Copyright (c) 2020 Nghia Nguyen. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

final class TVSeriesFormatter {
}

// MARK: - Extensions -

extension TVSeriesFormatter: TVSeriesFormatterInterface {

    func format(for input: TVSeries.FormatterInput) -> TVSeries.FormatterOutput {
        return TVSeries.FormatterOutput()
    }

}
