//
//  TVSeriesViewController.swift
//  Cinematics
//
//  Created by Nghia Nguyen on 5/31/20.
//  Copyright (c) 2020 Nghia Nguyen. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

final class TVSeriesViewController: UIViewController {

    // MARK: - Public properties -

    var presenter: TVSeriesPresenterInterface!

    // MARK: - Private properties -

    private let disposeBag = DisposeBag()

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        setupView()
    }

}

// MARK: - Extensions -

extension TVSeriesViewController: TVSeriesViewInterface {
}

private extension TVSeriesViewController {

    func setupView() {
        let output = TVSeries.ViewOutput()

        let input = presenter.configure(with: output)
    }

}
