//
//  TVSeriesInterfaces.swift
//  Cinematics
//
//  Created by Nghia Nguyen on 5/31/20.
//  Copyright (c) 2020 Nghia Nguyen. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

protocol TVSeriesWireframeInterface: WireframeInterface {
}

protocol TVSeriesViewInterface: ViewInterface {
}

protocol TVSeriesPresenterInterface: PresenterInterface {
    func configure(with output: TVSeries.ViewOutput) -> TVSeries.ViewInput
}

protocol TVSeriesFormatterInterface: FormatterInterface {
    func format(for input: TVSeries.FormatterInput) -> TVSeries.FormatterOutput
}

protocol TVSeriesInteractorInterface: InteractorInterface {
}

enum TVSeries {

    struct ViewOutput {
    }

    struct ViewInput {
        let models: FormatterOutput
    }

    struct FormatterInput {
    }

    struct FormatterOutput {
    }

}
