//
//  TVSeriesWireframe.swift
//  Cinematics
//
//  Created by Nghia Nguyen on 5/31/20.
//  Copyright (c) 2020 Nghia Nguyen. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

final class TVSeriesWireframe: BaseWireframe {

    // MARK: - Private properties -

    private let storyboard = UIStoryboard(name: "TVSeries", bundle: nil)

    // MARK: - Module setup -

    init() {
        let moduleViewController = storyboard.instantiateViewController(ofType: TVSeriesViewController.self)
        super.init(viewController: moduleViewController)

        let formatter = TVSeriesFormatter()
        let interactor = TVSeriesInteractor()
        let presenter = TVSeriesPresenter(view: moduleViewController, formatter: formatter, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension TVSeriesWireframe: TVSeriesWireframeInterface {
}
