# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

def shared_pods
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'Alamofire'
    pod 'ObjectMapper'
    pod 'CocoaLumberjack/Swift'
    pod 'DeviceKit'
    pod 'Kingfisher'
    pod 'SnapKit'
    pod 'SwiftDate'
    pod 'Then'
    pod 'Action'
    pod 'MBProgressHUD'
    pod 'LGButton'
    pod 'SwiftLint'
    pod 'R.swift'
end

target 'Moviek' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Moviek
  shared_pods

end

target 'Moviek Staging' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    # Pods for Moviek
    shared_pods
    
end

target 'Moviek Debug' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    # Pods for Moviek
    shared_pods
    
end
